"""
Static knowledge the extractor leans on: body types by model, colours, features.

Body type is the one field the listings almost never state, so it comes from
what the model name means. That is knowledge about the car model, not the
listing, and every value from here is tagged source=inferred.
"""

from __future__ import annotations

BODY_TYPE_BY_MODEL: dict[tuple[str, str], str] = {
    ("aston martin", "dbx"): "suv",
    ("aston martin", "vanquish"): "coupe",
    ("audi", "a3"): "sedan",
    ("audi", "a5"): "coupe",
    ("audi", "q7"): "suv",
    ("audi", "q8"): "suv",
    ("audi", "rs q3"): "suv",
    ("audi", "rs7"): "sedan",
    ("bentley", "bentayga"): "suv",
    ("bentley", "brooklands"): "coupe",
    ("bentley", "continental"): "coupe",
    ("bentley", "flying spur"): "sedan",
    ("bestune", "t99"): "suv",
    ("bmw", "2-series"): "coupe",
    ("bmw", "3-series"): "sedan",
    ("bmw", "i4"): "sedan",
    ("bmw", "ix3"): "suv",
    ("bmw", "m4"): "coupe",
    ("bmw", "m5"): "sedan",
    ("bmw", "x1"): "suv",
    ("bmw", "x6"): "suv",
    ("bugatti", "chiron"): "coupe",
    ("byd", "han"): "sedan",
    ("chery", "arrizo 5"): "sedan",
    ("chevrolet", "camaro"): "coupe",
    ("chevrolet", "captiva"): "suv",
    ("chevrolet", "malibu"): "sedan",
    ("chevrolet", "tahoe"): "suv",
    ("dodge", "challenger"): "coupe",
    ("dodge", "charger"): "sedan",
    ("ferrari", "f430"): "coupe",
    ("ferrari", "sf90 spider"): "convertible",
    ("ferrari", "sf90 stradale"): "coupe",
    ("ford", "edge"): "suv",
    ("ford", "explorer"): "suv",
    ("ford", "mustang"): "coupe",
    ("ford", "territory"): "suv",
    ("genesis", "g90"): "sedan",
    ("gwm", "wingle 5"): "pickup",
    ("haval", "h9"): "suv",
    ("honda", "cr-v"): "suv",
    ("hummer", "h3"): "suv",
    ("hyundai", "accent"): "sedan",
    ("hyundai", "genesis"): "sedan",
    ("hyundai", "tucson"): "suv",
    ("infiniti", "q50"): "sedan",
    ("jac", "js4"): "suv",
    ("jaguar", "f-pace"): "suv",
    ("jaguar", "xe"): "sedan",
    ("jeep", "wrangler"): "suv",
    ("kaiyi", "x7"): "suv",
    ("kia", "sportage"): "suv",
    ("lamborghini", "aventador"): "coupe",
    ("lamborghini", "revuelto"): "coupe",
    ("land rover", "discovery"): "suv",
    ("land rover", "lr4"): "suv",
    ("land rover", "range rover"): "suv",
    ("land rover", "range rover evoque"): "suv",
    ("land rover", "range rover sport"): "suv",
    ("land rover", "range rover velar"): "suv",
    ("lexus", "es-series"): "sedan",
    ("lexus", "lx-series"): "suv",
    ("lincoln", "aviator"): "suv",
    ("lincoln", "mkx"): "suv",
    ("maserati", "ghibli"): "sedan",
    ("maserati", "levante"): "suv",
    ("mazda", "3"): "sedan",
    ("mazda", "cx-5"): "suv",
    ("mclaren", "675lt"): "coupe",
    ("mercedes-benz", "a-class"): "hatchback",
    ("mercedes-benz", "c-class"): "sedan",
    ("mercedes-benz", "cla-class"): "sedan",
    ("mercedes-benz", "cls-class"): "sedan",
    ("mercedes-benz", "e-class"): "sedan",
    ("mercedes-benz", "g-class"): "suv",
    ("mercedes-benz", "g-class brabus"): "suv",
    ("mercedes-benz", "gla-class"): "suv",
    ("mercedes-benz", "glc coupe"): "suv",
    ("mercedes-benz", "glc-class"): "suv",
    ("mercedes-benz", "gle-class"): "suv",
    ("mercedes-benz", "glk-class"): "suv",
    ("mercedes-benz", "gls-class"): "suv",
    ("mercedes-benz", "s-class"): "sedan",
    ("mercedes-benz", "slr"): "coupe",
    ("mercedes-benz", "sprinter"): "van",
    ("mercedes-benz", "v-class"): "van",
    ("mini", "cooper"): "hatchback",
    ("mini", "countryman"): "suv",
    ("mitsubishi", "pajero"): "suv",
    ("mitsubishi", "pajero sport"): "suv",
    ("nissan", "altima"): "sedan",
    ("nissan", "kicks"): "suv",
    ("nissan", "maxima"): "sedan",
    ("nissan", "patrol"): "suv",
    ("nissan", "patrol safari"): "suv",
    ("nissan", "sunny"): "sedan",
    ("nissan", "versa"): "sedan",
    ("nissan", "x-trail"): "suv",
    ("nissan", "xterra"): "suv",
    ("opel", "grandland x"): "suv",
    ("peugeot", "landtrek"): "pickup",
    ("porsche", "cayenne"): "suv",
    ("renault", "megane"): "hatchback",
    ("rolls-royce", "cullinan"): "suv",
    ("rolls-royce", "dawn"): "convertible",
    ("rolls-royce", "ghost"): "sedan",
    ("rolls-royce", "phantom"): "sedan",
    ("rolls-royce", "wraith"): "coupe",
    ("tesla", "model x"): "suv",
    ("tova", "j14"): "truck_chassis",
    ("toyota", "bz4x"): "suv",
    ("toyota", "camry"): "sedan",
    ("toyota", "corolla"): "sedan",
    ("toyota", "hiace"): "van",
    ("toyota", "highlander"): "suv",
    ("toyota", "hilux"): "pickup",
    ("toyota", "innova"): "van",
    ("toyota", "land cruiser"): "suv",
    ("toyota", "land cruiser 70 series"): "pickup",
    ("toyota", "prado"): "suv",
    ("toyota", "rav 4"): "suv",
    ("toyota", "tundra"): "pickup",
    ("toyota", "urban cruiser"): "suv",
    ("toyota", "yaris"): "sedan",
    ("volkswagen", "beetle"): "hatchback",
    ("volkswagen", "golf"): "hatchback",
    ("volkswagen", "t-roc"): "suv",
    ("volvo", "xc60"): "suv",
    ("xiaomi", "yu7"): "suv",
}

# Words in the title or text that settle the body type regardless of the model map.
# "Coupe" and "sedan" are deliberately absent: the GLC Coupe is an SUV.
BODY_WORDS_STRONG: dict[str, str] = {
    "convertible": "convertible",
    "cabriolet": "convertible",
    "cabrio": "convertible",
    "roadster": "convertible",
    "spider": "convertible",
    "spyder": "convertible",
    "drophead": "convertible",
    "gtc": "convertible",
    "pickup": "pickup",
    "pick-up": "pickup",
    "double cab": "pickup",
    "chassis": "truck_chassis",
    "wagon": "wagon",
    "estate": "wagon",
    "stw": "wagon",
    "hatchback": "hatchback",
    "caravan": "van",
}

BODY_WORDS_WEAK: dict[str, str] = {
    "suv": "suv",
    "sedan": "sedan",
    "saloon": "sedan",
    "coupe": "coupe",
    "coupé": "coupe",
    "crossover": "suv",
    "van": "van",
}

ELECTRIC_MODELS = {
    ("bmw", "i4"),
    ("bmw", "ix3"),
    ("tesla", "model x"),
    ("byd", "han"),
    ("xiaomi", "yu7"),
    ("toyota", "bz4x"),
}

COLOR_WORDS: dict[str, str] = {
    "white": "white",
    "black": "black",
    "silver": "silver",
    "grey": "grey",
    "gray": "grey",
    "red": "red",
    "blue": "blue",
    "beige": "beige",
    "brown": "brown",
    "green": "green",
    "orange": "orange",
    "gold": "gold",
    "yellow": "yellow",
    "maroon": "maroon",
    "burgundy": "maroon",
    "purple": "purple",
    "bronze": "bronze",
    "champagne": "champagne",
    "navy": "blue",
    "havana": "brown",
    # Arabic, with and without the definite article
    "أبيض": "white",
    "ابيض": "white",
    "الأبيض": "white",
    "الابيض": "white",
    "أسود": "black",
    "اسود": "black",
    "الأسود": "black",
    "الاسود": "black",
    "فضي": "silver",
    "الفضي": "silver",
    "رمادي": "grey",
    "الرمادي": "grey",
    "أحمر": "red",
    "احمر": "red",
    "الأحمر": "red",
    "أزرق": "blue",
    "ازرق": "blue",
    "بيج": "beige",
    "البيج": "beige",
    "بني": "brown",
    "أخضر": "green",
    "اخضر": "green",
    "ذهبي": "gold",
    "أصفر": "yellow",
    "برتقالي": "orange",
}

# Phrases where a colour word is a trim name or an interior, not the paint.
COLOR_FALSE_FRIENDS = (
    "black edition",
    "black badge",
    "shadow line",
    "black package",
    "black pack",
    "night package",
    "black kit",
    "blackout",
    "black optic",
    "black series",
)

REGIONAL_SPEC_PATTERNS: list[tuple[str, str]] = [
    (r"\bgcc\b|\bgulf\b|خليجي|خليجية|وارد الخليج", "gcc"),
    (r"\bamerican\b|\bus\s*specs?\b|\busa\b|\bus\s+space\b|امريكي|أمريكي|امريكية|أمريكية", "us"),
    (r"\bjapan|\bjapanese\b|ياباني", "japan"),
    (r"\beuro\b|\beuropean\b|اوروبي|أوروبي", "euro"),
    (r"\bkorean\b|كوري", "korean"),
    (r"\bcanadian\b|كندي", "canadian"),
]

FEATURE_KEYWORDS: dict[str, str] = {
    "panoramic": "panoramic roof",
    "panorama": "panoramic roof",
    "sunroof": "sunroof",
    "leather": "leather",
    "carplay": "apple carplay",
    "android auto": "android auto",
    "360": "360 camera",
    "camera": "camera",
    "cruise": "cruise control",
    "navigation": "navigation",
    "keyless": "keyless",
    "heated": "heated seats",
    "cooled": "cooled seats",
    "ventilated": "ventilated seats",
    "massage": "massage seats",
    "4wd": "4wd",
    "awd": "awd",
    "4x4": "4x4",
    "7 seat": "7 seats",
    "seven seat": "7 seats",
    "burmester": "burmester audio",
    "bose": "bose audio",
    "harman": "harman kardon audio",
    "head-up": "head-up display",
    "heads up": "head-up display",
    "hud": "head-up display",
    "adaptive cruise": "adaptive cruise",
    "lane": "lane assist",
    "blind spot": "blind spot monitor",
    "ceramic": "ceramic coating",
    "ppf": "paint protection",
    "full option": "full option",
    "top option": "full option",
    "fully loaded": "full option",
    "body kit": "body kit",
    "bodykit": "body kit",
    "m sport": "m sport",
    "amg": "amg",
    "diesel": "diesel",
    "petrol": "petrol",
    "hybrid": "hybrid",
    "electric": "electric",
    "turbo": "turbo",
    "v6": "v6",
    "v8": "v8",
    "v12": "v12",
    "automatic": "automatic",
    "manual": "manual",
    "service history": "service history",
    "fsh": "full service history",
    "accident free": "accident free",
    "no accident": "accident free",
    "original paint": "original paint",
    "no paint": "original paint",
    "clean title": "clean title",
    "one owner": "single owner",
    "1 owner": "single owner",
    "single hand": "single owner",
    "agency": "agency maintained",
    "warranty": "warranty",
    "service contract": "service contract",
    "low mileage": "low mileage",
    "brand new": "brand new",
    "0 km": "brand new",
    "0km": "brand new",
    "financ": "financing available",
    "0% down": "zero down payment",
    "trade in": "trade-in accepted",
    "trade-in": "trade-in accepted",
    "export": "export",
    "inspected": "inspected",
}

# Arabic terms that carry facts the English search would otherwise miss.
ARABIC_GLOSSARY: dict[str, str] = {
    "فل": "full option",
    "فل اوبشن": "full option",
    "فل كامل": "full option",
    "بانوراما": "panoramic roof",
    "فتحة": "sunroof",
    "ضمان": "warranty",
    "عقد صيانة": "service contract",
    "صيانة": "service",
    "وكالة": "agency maintained",
    "جمارك": "customs papers",
    "أوراق جمارك": "customs papers",
    "كاش": "cash",
    "بنك": "bank finance",
    "تمويل": "financing available",
    "تقسيط": "instalments",
    "بدون دفعة": "zero down payment",
    "بدون دفعه": "zero down payment",
    "خليجي": "gcc spec",
    "خليجية": "gcc spec",
    "نظيفة": "clean",
    "نظيف": "clean",
    "بحالة ممتازة": "excellent condition",
    "بحاله ممتازه": "excellent condition",
    "حادث": "accident",
    "بدون حوادث": "accident free",
    "صبغ": "paint",
    "جلد": "leather",
    "شاشة": "screen",
    "شاشه": "screen",
    "كاميرا": "camera",
    "كامرا": "camera",
    "كمرات": "cameras",
    "رنجات": "rims",
    "دفع رباعي": "4wd",
    "العداد": "odometer",
    "ممشى": "mileage",
    "قابل للتفاوض": "negotiable",
    "سوبر سفاري": "super safari",
    "بصمة": "keyless",
    "بصمه": "keyless",
    "رادار": "radar",
    "تسخين": "heated seats",
    "تبريد": "cooled seats",
    "سياقة ذاتية": "driver assist",
    "سياقه ذاتيه": "driver assist",
    "دبة كهرباء": "power tailgate",
    "خالية من العيوب": "no faults",
}

# The dubizzle managed-inventory block that sits at the bottom of ten raw listings.
MANAGED_MARKERS = (
    "what is dubizzle cars",
    "buy this car with confidence from dubizzle cars",
    "what to expect from dubizzle cars",
)

# Dealer paragraphs that repeat across unrelated cars and say nothing about the car.
BOILERPLATE_MARKERS = (
    "alhoot motors deals with gcc cars only",
    "we have direct access more then 160 auctions",
    "a name you can trust",
    "a decade of experience in luxury car selling",
)

EXPORT_ONLY_RE = (
    r"\bexport\s+only\b|\bonly\s+for\s+export\b|\bfor\s+export\s+only\b"
    r"|\bavailable\s+only\s+for\s+export\b|\(export only\)"
)

DEALER_NAME_RE = (
    r"\b((?:Al[- ][A-Z][\w']+|[A-Z][\w'&\-]+)(?:\s+(?:Al[- ][A-Z][\w']+|[A-Z][\w'&\-]+)){0,3}"
    r"\s+(?:Motors|Cars|Auto|Automobile|Automobiles|Autos|Used Cars|Car Trading|Motor|Automotive))\b"
)
