[browser]
gatherUsageStats = false

[server]
showEmailPrompt = false

[theme]
base = "dark"
primaryColor = "#E3262E"
backgroundColor = "#0F0F10"
secondaryBackgroundColor = "#18181A"
textColor = "#F4F4F5"
font = "sans serif"
